from __future__ import annotations

import sys
from pathlib import Path
from rdflib import Graph

# Turtle file generated by export_ontology_v1_to_ttl.py
IN_TTL = Path("data/processed/edi_ontology_v1.ttl")


def main() -> None:
    """Attempt to parse the TTL file and report whether validation passed."""
    if not IN_TTL.exists():
        print(f" TTL validation: FAIL (missing file: {IN_TTL})")
        sys.exit(1)

    graph = Graph()

    try:
        # Parse as Turtle syntax.
        graph.parse(IN_TTL.as_posix(), format="turtle")
    except Exception as e:
        print(" TTL validation: FAIL (rdflib could not parse the file)")
        print(f"File: {IN_TTL}")
        print(f"Error: {e}")
        sys.exit(1)

    print(" TTL validation: PASS (parsed successfully)")
    print(f"File: {IN_TTL}")
    print(f"Triples loaded: {len(graph)}")

    sys.exit(0)


if __name__ == "__main__":
    main()